import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/providers/react-query-provider";
import { Toaster } from "@/components/ui/toast";

export const metadata: Metadata = {
  title: "TEMP Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          {children}
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
